/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewReservations.java
 *
 * Created on Apr 6, 2012, 6:36:50 PM
 */
package vehiclereservationsystem;

import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nimos
 */
public class ViewReservations extends javax.swing.JFrame {

    /** Creates new form ViewReservations */
    public ViewReservations() {
        initComponents();
        try {
            ResultSet r = SQL.getDetailsOfReservations();
            DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
            while (r.next()) {
                Vector v = new Vector();
                v.add(r.getString("vehicle"));
                v.add(r.getString("travel_guide"));
                v.add(r.getString("from_date"));
                v.add(r.getString("to_date"));
                v.add(r.getString("approved_officer"));
                v.add(r.getString("approved_date_time"));
                dtm.addRow(v);
            }

        } catch (Exception ex) {
            Logger.getLogger(ViewReservations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle", "Travel Guide Name", "Starting Date", "Ending Date", "Approved Officer", "Approved Date"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Approve or Reject selected entry");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedIndex = tbl.getSelectedRow();
        System.out.println(selectedIndex);
        if (selectedIndex != -1) {
            String vehicle = tbl.getValueAt(selectedIndex, 0).toString();
            String travelGuide = tbl.getValueAt(selectedIndex, 1).toString();
            String fromDate = tbl.getValueAt(selectedIndex, 2).toString();
            String toDate = tbl.getValueAt(selectedIndex, 3).toString();
            try {
                ResultSet selectedRow = SQL.getSelectedReservation(vehicle, travelGuide, fromDate, toDate);
                ApproveReservations ap = new ApproveReservations();
                ap.r = selectedRow;
                ap.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a reservation in order to continue.");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewReservations().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
